global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['telegram_bot:8001']
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8010']