"""empty message

Revision ID: bf87daa1727d
Revises: 
Create Date: 2024-12-26 10:31:18.985676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf87daa1727d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'person',
        sa.Column('telegram_id', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
        schema='public',
    )
    op.create_index(op.f('ix_public_person_telegram_id'), 'person', ['telegram_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_person_username'), 'person', ['username'], unique=False, schema='public')
    op.create_table(
        'music',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('author', sa.Uuid(), nullable=False),
        sa.Column('genre', sa.String(), nullable=False),
        sa.Column('streams', sa.Integer(), nullable=True),
        sa.Column('file_url', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['author'], ['public.person.id'], name=op.f('fk_music_author_person')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_music')),
        schema='public',
    )
    op.create_index(op.f('ix_public_music_title'), 'music', ['title'], unique=False, schema='public')
    op.create_table(
        'usermusic',
        sa.Column('person', sa.Uuid(), nullable=False),
        sa.Column('music', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['music'], ['public.music.id'], name=op.f('fk_usermusic_music_music')),
        sa.ForeignKeyConstraint(['person'], ['public.person.id'], name=op.f('fk_usermusic_person_person')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_usermusic')),
        sa.UniqueConstraint('person', 'music', name='uq_user_music'),
        schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermusic', schema='public')
    op.drop_index(op.f('ix_public_music_title'), table_name='music', schema='public')
    op.drop_table('music', schema='public')
    op.drop_index(op.f('ix_public_person_username'), table_name='person', schema='public')
    op.drop_index(op.f('ix_public_person_telegram_id'), table_name='person', schema='public')
    op.drop_table('person', schema='public')
    # ### end Alembic commands ###
