version: 1
disable_existing_loggers: False

formatters:
  console_formatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: console_formatter
    level: INFO

loggers:
  consumer_logger:
    level: INFO
    handlers: [console]
    propagate: no
